"""Shared package constants."""

DEFAULT_OUTPUT_FOLDER = "output"
DEFAULT_RESULTS_FOLDER = "results"
GOLD_STANDARD_FOLDER = "concept_extractor"
DEFAULT_EXTRACTION_OUTPUT_DIR = f"{DEFAULT_OUTPUT_FOLDER}/{GOLD_STANDARD_FOLDER}/{DEFAULT_RESULTS_FOLDER}"
